---
- name: Create New Users
  hosts: all
  gather_facts: true
  tasks:
    
    - name: Create Users Task
      user:
        name: "{{ item }}"
        state: present
        password: "{{ default_user_password | password_hash('sha512', 'A512') }}"
        shell: /bin/bash
        groups: "{{ admin_group }}"
      loop:
        - ali
        - hasan
        - reza
        - pary

...
