---
- name: Clean User Accounts
  hosts: all
  gather_facts: true
  become: true
  tasks:

    - name: Delete Users
      user:
        name: "{{ item }}"
        state: absent
        remove: true
      loop:
        - ali
        - hasan
        - reza
        - pary
